---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: base-cluster
  namespace: flux-system
spec:
  chart:
    spec:
      chart: base-cluster
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: teuto-net
        namespace: flux-system
      version: 9.x.x
  interval: 1m0s
