apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: base-cluster
  namespace: flux-system
spec:
  chart:
    spec:
      chart: base-cluster
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: teuto-net
        namespace: flux-system
      version: 9.x.x
  interval: 1m0s
  values:
    global:
      clusterName: 1111-workshop-00
    flux:
      gitRepositories:
        main:
          url: https://github.com/jadasswad/kubernetesschulung
          branch: main
